export interface ExtensionSeed {
  id: string;
  name: string;
  description: string;
  version: string;
  author: string;
  category: string;
  icon: string;
  color: string;
  rating: number;
  downloads: number;
  homepage?: string;
  repository?: string;
  tags: string[];
  instructions?: string;
}

export const EXTENSIONS_SEED: ExtensionSeed[] = [
  {
    id: 'ext_markdown_render',
    name: 'Markdown 渲染器',
    description: '在对话中渲染 Markdown 内容，支持代码高亮、表格、数学公式等。',
    version: '1.2.0',
    author: 'Ice Cola Team',
    category: 'tool',
    icon: '📝',
    color: '#3B82F6',
    rating: 4.8,
    downloads: 25600,
    tags: ['markdown', '渲染', '格式化'],
    instructions: '自动将对话中的 Markdown 文本渲染为富文本格式。',
  },
  {
    id: 'ext_code_runner',
    name: '代码运行器',
    description: '在沙箱环境中执行代码片段，支持 JavaScript、Python、TypeScript。',
    version: '2.0.0',
    author: 'Ice Cola Team',
    category: 'tool',
    icon: '▶️',
    color: '#10B981',
    rating: 4.7,
    downloads: 18900,
    tags: ['代码', '执行', '沙箱'],
    instructions: '在安全的沙箱环境中运行用户提供的代码片段。',
  },
  {
    id: 'ext_web_search',
    name: '网络搜索',
    description: '允许 AI 助手搜索互联网获取实时信息。',
    version: '1.5.0',
    author: 'Ice Cola Team',
    category: 'tool',
    icon: '🔍',
    color: '#F59E0B',
    rating: 4.6,
    downloads: 32100,
    tags: ['搜索', '网络', '信息'],
    instructions: '启用网络搜索功能，让 AI 可以获取最新的互联网信息。',
  },
  {
    id: 'ext_file_manager',
    name: '文件管理器',
    description: '在对话中创建、读取、编辑和管理本地文件。',
    version: '1.3.0',
    author: 'Ice Cola Team',
    category: 'tool',
    icon: '📁',
    color: '#8B5CF6',
    rating: 4.5,
    downloads: 15400,
    tags: ['文件', '管理', '本地'],
    instructions: '允许 AI 助手管理本地文件系统中的文件。',
  },
  {
    id: 'ext_image_gen',
    name: '图像生成',
    description: '通过 AI 模型生成图像，支持文生图和图生图。',
    version: '1.1.0',
    author: 'Ice Cola Team',
    category: 'creative',
    icon: '🎨',
    color: '#EC4899',
    rating: 4.4,
    downloads: 12800,
    tags: ['图像', '生成', 'AI'],
    instructions: '启用 AI 图像生成功能，根据文字描述创建图像。',
  },
  {
    id: 'ext_data_viz',
    name: '数据可视化',
    description: '将数据转换为图表和可视化展示，支持折线图、柱状图、饼图等。',
    version: '1.0.0',
    author: 'Ice Cola Team',
    category: 'tool',
    icon: '📊',
    color: '#EF4444',
    rating: 4.3,
    downloads: 9800,
    tags: ['数据', '可视化', '图表'],
    instructions: '将对话中的数据自动转换为可视化图表。',
  },
  {
    id: 'ext_translate',
    name: '多语言翻译',
    description: '支持 100+ 语言的实时翻译，包括技术文档翻译。',
    version: '1.4.0',
    author: 'Ice Cola Team',
    category: 'tool',
    icon: '🌍',
    color: '#06B6D4',
    rating: 4.6,
    downloads: 21500,
    tags: ['翻译', '多语言', '国际化'],
    instructions: '启用多语言翻译功能，支持对话内容的实时翻译。',
  },
  {
    id: 'ext_voice_input',
    name: '语音输入',
    description: '支持语音转文字输入，提高对话效率。',
    version: '1.0.0',
    author: 'Ice Cola Team',
    category: 'tool',
    icon: '🎤',
    color: '#6366F1',
    rating: 4.2,
    downloads: 8700,
    tags: ['语音', '输入', '转文字'],
    instructions: '启用语音识别功能，将语音输入转换为文字。',
  },
  {
    id: 'ext_export_pdf',
    name: 'PDF 导出',
    description: '将对话内容导出为格式化的 PDF 文档。',
    version: '1.1.0',
    author: 'Ice Cola Team',
    category: 'tool',
    icon: '📄',
    color: '#F97316',
    rating: 4.4,
    downloads: 11200,
    tags: ['PDF', '导出', '文档'],
    instructions: '将当前对话内容导出为 PDF 格式的文档。',
  },
  {
    id: 'ext_workflow',
    name: '工作流自动化',
    description: '创建和管理自动化工作流，连接多个服务和操作。',
    version: '1.0.0',
    author: 'Ice Cola Team',
    category: 'automation',
    icon: '⚡',
    color: '#84CC16',
    rating: 4.3,
    downloads: 7600,
    tags: ['工作流', '自动化', '集成'],
    instructions: '创建自动化工作流，将重复任务交给 AI 处理。',
  },
];
