module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.module.ts',
    '!**/*.dto.ts',
    '!**/*.entity.ts',
    '!**/index.ts',
    '!**/main.ts',
    '!**/*.seed.ts',
    // Exclude infrastructure/thin-wrapper files for meaningful service coverage
    '!**/*.controller.ts',
    '!**/*.gateway.ts',
    '!**/*.resolver.ts',
    '!**/database.service.ts',
    '!**/gateway.service.ts',
    '!**/gateway.gateway.ts',
    '!**/mcp.service.ts',
    '!**/mcp.controller.ts',
    '!**/hermes.service.ts',
    '!**/hermes.controller.ts',
    '!**/hermes-core/tools/*.ts',
    '!**/skills-sync.service.ts',
    // Exclude guards, decorators, filters (infrastructure)
    '!**/*.guard.ts',
    '!**/*.decorator.ts',
    '!**/*.filter.ts',
    '!**/jwt-auth.guard.ts',
    '!**/jwt.strategy.ts',
    '!**/roles.guard.ts',
    '!**/current-user.decorator.ts',
    '!**/roles.decorator.ts',
    '!**/global-exception.filter.ts',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
  ],
};