-- Seed data for extensions table
-- Run this after database initialization to populate extension marketplace

INSERT INTO extensions (id, name, description, version, author, category, icon, color, rating, downloads, homepage, repository, enabled) VALUES
(
  'ext-github-001',
  'GitHub 集成',
  '无缝连接 GitHub，管理仓库、PR 和 Issues。支持代码审查、Issue 自动分类、PR 模板生成等功能。',
  '1.2.0',
  'OpenClaw Team',
  '开发工具',
  '🐙',
  '#24292F',
  4.8,
  15234,
  'https://github.com/openclaw/ext-github',
  'https://github.com/openclaw/ext-github',
  true
),
(
  'ext-notion-001',
  'Notion 连接器',
  '将 AI 助手与 Notion 工作区集成，自动同步笔记和数据库。支持页面创建、内容更新、数据库查询等操作。',
  '0.9.5',
  'Community',
  '生产力',
  '📝',
  '#000000',
  4.5,
  8921,
  'https://github.com/openclaw/ext-notion',
  'https://github.com/openclaw/ext-notion',
  true
),
(
  'ext-slack-001',
  'Slack 机器人',
  '在 Slack 中使用 AI 助手，团队协作更智能。支持消息回复、频道管理、自动化工作流等功能。',
  '2.0.1',
  'OpenClaw Team',
  '通讯',
  '💬',
  '#4A154B',
  4.7,
  12456,
  'https://github.com/openclaw/ext-slack',
  'https://github.com/openclaw/ext-slack',
  true
),
(
  'ext-vscode-001',
  'VS Code 插件',
  '在 VS Code 中直接使用 AI 助手，代码补全和审查。支持智能代码建议、错误修复、重构建议等。',
  '1.5.3',
  'OpenClaw Team',
  '开发工具',
  '💻',
  '#007ACC',
  4.9,
  23456,
  'https://marketplace.visualstudio.com/items?itemName=openclaw.ai',
  'https://github.com/openclaw/vscode-extension',
  true
),
(
  'ext-calendar-001',
  '日历助手',
  '智能日程管理，自动安排会议和提醒。支持与 Google Calendar、Outlook 等日历服务集成。',
  '0.8.2',
  'Community',
  '生产力',
  '📅',
  '#4285F4',
  4.3,
  6789,
  'https://github.com/openclaw/ext-calendar',
  'https://github.com/openclaw/ext-calendar',
  true
),
(
  'ext-translate-001',
  '实时翻译',
  '支持 50+ 语言的实时翻译，打破语言障碍。使用先进的神经机器翻译技术，提供准确的翻译结果。',
  '1.1.0',
  'Community',
  '工具',
  '🌐',
  '#FF6B6B',
  4.6,
  11234,
  'https://github.com/openclaw/ext-translate',
  'https://github.com/openclaw/ext-translate',
  true
),
(
  'ext-weather-001',
  '天气插件',
  '实时天气信息和预报，支持全球城市。提供详细的天气预报、空气质量指数、穿衣建议等。',
  '0.5.1',
  'Community',
  '工具',
  '⛅',
  '#FFA500',
  4.2,
  5432,
  'https://github.com/openclaw/ext-weather',
  'https://github.com/openclaw/ext-weather',
  true
),
(
  'ext-pdf-001',
  'PDF 处理器',
  '智能 PDF 解析、摘要和问答。支持文本提取、表格识别、图像 OCR、文档摘要等功能。',
  '1.3.2',
  'OpenClaw Team',
  '文档',
  '📄',
  '#E74C3C',
  4.7,
  9876,
  'https://github.com/openclaw/ext-pdf',
  'https://github.com/openclaw/ext-pdf',
  true
);
